[context.production.environment]
[context.deploy-preview.environment]
[context.staging.environment]
[context.qa.environment]
[context.dev.environment]

[build]
functions = "functions"
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[functions]
external_node_modules = ["express", "@sentry/serverless", "superagent-proxy"]
